---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-8.3

suites:
  - name: workstation-default
    run_list:
      - recipe[chef-workstation::default]

  - name: workstation-desktop
    run_list:
      - recipe[chef-workstation::desktop]

  - name: workstation-apt
    run_list:
      - recipe[chef-workstation::apt]

  - name: workstation-laptop
    run_list:
      - recipe[chef-workstation::laptop]
