---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-8.3

suites:
  - name: apt
    run_list:
      - recipe[chef-workstation::apt]

  # needs tests
  - name: default
    run_list:
      - recipe[chef-workstation::default]

  # needs tests
  - name: desktop
    run_list:
      - recipe[chef-workstation::desktop]

  - name: disable_internal_speaker
    run_list:
      - recipe[chef-workstation::disable_internal_speaker]

  - name: i3
    run_list:
      - recipe[chef-workstation::i3]

  # needs tests
  - name: laptop
    run_list:
      - recipe[chef-workstation::laptop]

  - name: nvidia
    run_list:
      - recipe[chef-workstation::nvidia]

  - name: intel_wifi
    run_list:
      - recipe[chef-workstation::intel_wifi]

  - name: user
    run_list:
      - recipe[chef-workstation::user]
