---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.3

suites:
  - name: workstation
    run_list:
      - recipe[workstation::default]
