---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-8.3

suites:
  - name: desktop
    run_list:
      - recipe[workstation::desktop]

  - name: laptop
    run_list:
      - recipe[workstation::laptop]

  - name: nvidia
    run_list:
      - recipe[workstation::nvidia]
