---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-8.3

suites:
  - name: apt
    run_list:
      - recipe[chef-workstation::apt]

  - name: default
    run_list:
      - recipe[chef-workstation::default]

  - name: desktop
    run_list:
      - recipe[chef-workstation::desktop]

  - name: disable_internal_speaker
    run_list:
      - recipe[chef-workstation::disable_internal_speaker]

  - name: laptop
    run_list:
      - recipe[chef-workstation::laptop]

  - name: nvidia
    run_list:
      - recipe[chef-workstation::nvidia]
