---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-8.3

suites:
  - name: apt
    run_list:
      - recipe[workstation::apt]

  - name: configs
    run_list:
      - recipe[workstation::configs]

  - name: default
    run_list:
      - recipe[workstation::default]

  - name: desktop
    run_list:
      - recipe[workstation::desktop]

  - name: disable_internal_speaker
    run_list:
      - recipe[workstation::disable_internal_speaker]

  - name: i3
    run_list:
      - recipe[workstation::i3]

  - name: intel_wifi
    run_list:
      - recipe[workstation::intel_wifi]

  - name: laptop
    run_list:
      - recipe[workstation::laptop]

  - name: nvidia
    run_list:
      - recipe[workstation::nvidia]

  - name: ruby
    run_list:
      - recipe[workstation::ruby]

  - name: user
    run_list:
      - recipe[workstation::user]
    attributes:
      desktop:
        user:
          name: 'test_user'
          uid: '2000'
          group: 'test_user'
          gid: '2000'
          home: '/home/test_user'

