---
driver:
  name: vagrant
  # name: docker -- TODO setup docker as test driver

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-8.3

suites:
  # TODO figure out how to specify apt repository that system uses for non-apt recipes. Do they use apt even?
  - name: apt
    run_list:
      - recipe[workstation::apt]

  - name: configs
    run_list:
      - recipe[workstation::configs]

  # needs tests
  - name: default
    run_list:
      - recipe[workstation::default]

  # needs tests
  - name: desktop
    run_list:
      - recipe[workstation::desktop]

  - name: disable_internal_speaker
    run_list:
      - recipe[workstation::disable_internal_speaker]

  - name: i3
    run_list:
      - recipe[workstation::i3]

  - name: intel_wifi
    run_list:
      - recipe[workstation::intel_wifi]

  # needs tests
  - name: laptop
    run_list:
      - recipe[workstation::laptop]

  - name: nvidia
    run_list:
      - recipe[workstation::nvidia]

  - name: ruby
    run_list:
      - recipe[workstation::ruby]

  - name: user
    run_list:
      - recipe[workstation::user]
